# Generated by Django 3.2.7 on 2021-10-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('dept_id', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first_name', models.CharField(max_length=20)),
                ('emp_last_name', models.CharField(max_length=20)),
                ('emp_designation', models.CharField(max_length=50)),
                ('emp_salary', models.IntegerField(max_length=8)),
                ('emp_id', models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='django_app.department')),
            ],
        ),
    ]
