# Generated by Django 3.2.7 on 2022-08-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20211001_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
